#!/usr/bin/env python3
"""Build MUST-PASS summary tables (M1-M8)."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build MUST-PASS tables from run outputs.")
    parser.add_argument(
        "--status",
        type=Path,
        default=PROJECT_ROOT / "runs/must_pass_status.json",
        help="Status JSON generated by run_must_pass.py",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        default=PROJECT_ROOT / "runs/must_tables",
        help="Output directory for MUST tables.",
    )
    return parser.parse_args()


def _read_json(path: Path):
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _resolve_run_root(exp_id: str) -> Path:
    special = {
        "M8-cross-domain": PROJECT_ROOT / "runs/E5_cross_domain",
    }
    if exp_id in special:
        return special[exp_id]
    if exp_id.startswith("M1-"):
        suffix = "low_temp" if "low" in exp_id else "high_temp"
        return PROJECT_ROOT / "runs/must/M1" / suffix
    if exp_id.startswith("M2-"):
        suffix = "with_context" if "with" in exp_id else "no_context"
        return PROJECT_ROOT / "runs/must/M2" / suffix
    if exp_id.startswith("M3-"):
        return PROJECT_ROOT / "runs/must/M3/policies"
    if exp_id.startswith("M4-current"):
        return PROJECT_ROOT / "runs/must/M4/current_best"
    if exp_id.startswith("M4-stability"):
        return PROJECT_ROOT / "runs/must/M4/stability_aware"
    if exp_id.startswith("M5-no-shacl"):
        return PROJECT_ROOT / "runs/must/M5/no_shacl"
    if exp_id.startswith("M5-no-reasoning"):
        return PROJECT_ROOT / "runs/must/M5/no_reasoning"
    if exp_id.startswith("M5-no-cq"):
        return PROJECT_ROOT / "runs/must/M5/no_cq"
    if exp_id.startswith("M6-"):
        return PROJECT_ROOT / "runs/must/M6/iteration_dynamics"
    if exp_id.startswith("M7-"):
        return PROJECT_ROOT / "runs/must/M7/error_taxonomy"
    return PROJECT_ROOT / "runs/must" / exp_id


def _metric_f1(run_root: Path) -> float | None:
    for path in [run_root / "final/metrics_semantic.json", run_root / "metrics_semantic.json"]:
        payload = _read_json(path)
        if isinstance(payload, dict):
            return payload.get("f1")
    return None


def _cq_rate(run_root: Path) -> float | None:
    for path in [run_root / "final/cq_results.json", run_root / "cq_results.json"]:
        payload = _read_json(path)
        if isinstance(payload, dict):
            return payload.get("pass_rate")
    return None


def _error_count(run_root: Path) -> int:
    payload = _read_json(run_root / "diagnostics_summary.json")
    if not isinstance(payload, dict):
        return 0
    total = 0
    for row in payload.get("rows", []) or []:
        if isinstance(row, dict):
            total += len(row.get("error_taxonomy", []) or [])
    return total


def _write_csv(path: Path, rows: list[dict], headers: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=headers)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key) for key in headers})


def main() -> None:
    args = parse_args()
    status = _read_json(args.status)
    if not isinstance(status, list):
        raise SystemExit(f"Missing status file: {args.status}")

    rows = []
    for item in status:
        if not isinstance(item, dict):
            continue
        exp_id = str(item.get("id", ""))
        run_root = _resolve_run_root(exp_id)
        rows.append(
            {
                "must_id": item.get("must_id"),
                "id": exp_id,
                "name": item.get("name"),
                "exit_code": item.get("exit_code"),
                "runtime_seconds": item.get("runtime_seconds"),
                "f1_semantic": _metric_f1(run_root),
                "cq_pass_rate": _cq_rate(run_root),
                "taxonomy_events": _error_count(run_root),
                "run_root": str(run_root),
            }
        )

    _write_csv(
        args.outdir / "must_pass_results.csv",
        rows,
        ["must_id", "id", "name", "exit_code", "runtime_seconds", "f1_semantic", "cq_pass_rate", "taxonomy_events", "run_root"],
    )
    print(f"Wrote MUST tables -> {args.outdir}")


if __name__ == "__main__":
    main()
